export const language: string[] = [
  "English",
  "MandarinChinese",
  "Hindi",
  "Spanish",
  "StandardArabic",
  "Bengali",
  "Russian",
  "Portuguese",
  "Urdu",
  "Indonesian",
  "German",
  "Japanese",
  "NigerianPidgin",
  "Marathi",
  "Telugu",
  "Turkish",
  "Tamil",
  "YueChinese",
  "Vietnamese",
  "Tagalog",
  "WuChinese",
  "Korean",
  "IranianPersianFarsi",
  "Hausa",
  "EgyptianSpokenArabic",
  "Swahili",
  "Javanese",
  "Italian",
  "WesternPunjabi",
  "Kannada",
  "Gujarati",
  "Thai",
];

export const level: string[] = ["A1", "A2", "B1", "B2", "C1", "C2"];
